export const futsal_female = [
    {
        team1: 'TEAM 1',
        team2: 'TEAM 2',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: '16:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'TEAM 2',
        team2: 'TEAM 3',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: '17:15',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'TEAM 3',
        team2: 'TEAM 1',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: '18:00',
        week: 1,
        location: 'Court 1',
    },
]

export const futsal_male = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '3/4/2025',
        time: '16:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '3/4/2025',
        time: '17:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '3/4/2025',
        time: '17:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '3/4/2025',
        time: '18:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '3/4/2025',
        time: '19:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '8/4/2025',
        time: '16:30',
        week: 3,
        location: 'Court 1',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '8/4/2025',
        time: '17:10',
        week: 3,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '8/4/2025',
        time: '17:50',
        week: 3,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '8/4/2025',
        time: '18:30',
        week: 3,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '8/4/2025',
        time: '19:10',
        week: 3,
        location: 'Court 1',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '17:10',
        week: 'Final',
        location: 'Court 1',
    },
]

export const basketball_male = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: '18:00',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: '18:45',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: '19:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '18:00',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '18:45',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '1/4/2025',
        time: '18:00',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '1/4/2025',
        time: '18:45',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '1/4/2025',
        time: '19:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '18:00',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '18:45',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '19:00',
        week: 3,
        location: 'Court 1',
    },
]

export const basketball_female = [
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:00',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 2',
        team2: 'Team 3',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:45',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 3',
        team2: 'Team 1',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '19:30',
        week: 1,
        location: 'Court 1',
    },
]

export const chairball_female = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '16:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '17:10',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '17:50',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '18:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: '19:10',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '16:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '17:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '17:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '18:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        date: '2/4/2025',
        time: '19:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '16:30',
        week: 'Final',
        location: 'Court 1',
    },
]

export const badminton_male = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '16:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '16:30',
        week: 1,
        location: 'Court 2',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '16:50',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '16:50',
        week: 1,
        location: 'Court 2',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:10',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:10',
        week: 1,
        location: 'Court 2',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:30',
        week: 1,
        location: 'Court 2',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:50',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '17:50',
        week: 1,
        location: 'Court 2',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '18:10',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '18:10',
        week: 1,
        location: 'Court 2',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 2',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '18:30',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '18:30',
        week: 1,
        location: 'Court 2',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: '18:50',
        week: 1,
        location: 'Court 1',
    },

    // Week 2 ====================================================================================================
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '16:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '16:30',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '16:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '16:50',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:10',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:30',
        week: 2,
        location: 'Court 2',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '17:50',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:10',
        week: 2,
        location: 'Court 2',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 3',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner of Quarter Final Match 2',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:30',
        week: 2,
        location: 'Court 2',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        date: '4/4/2025',
        time: '18:50',
        week: 2,
        location: 'Court 1',
    },
    //Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '17:50',
        week: 3,
        location: 'Court 1',
    },
]

export const badminton_female = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '16:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '16:30',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '16:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '16:50',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:10',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:30',
        week: 2,
        location: 'Court 2',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:50',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '17:50',
        week: 2,
        location: 'Court 2',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '18:10',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '18:10',
        week: 2,
        location: 'Court 2',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 2',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '18:30',
        week: 2,
        location: 'Court 1',
    },
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '18:30',
        week: 2,
        location: 'Court 2',
    },
    // Finalist
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        date: '31/3/2025',
        time: '18:30',
        week: 2,
        location: 'Court 2',
    },
    //Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '17:50',
        week: 3,
        location: 'Court 2',
    },
]

export const rov_mixed = [
    // Week 1 - ROV - Tuesday 25th March - Quarter Final Stage (Bo3)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 3',
        team2: 'Team 4',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 5',
        team2: 'Team 6',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 7',
        team2: 'Team 8',
        score1: 0,
        score2: 0,
        date: '25/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },

    // Week 1 - ROV - Thursday 27th March - Semi-Final Stage (Bo3)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 3',
        team2: 'Team 4',
        score1: 0,
        score2: 0,
        date: '27/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },

    // Week 3 - ROV - Wednesday 9th April - Grand Final Stage (Bo5)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '20:00',
        week: 3,
        location: 'Court 1',
    },
]

export const valorant_mixed = [
    // Week 1 - Valorant - Monday 24th March - Quarter Final Stage (Bo3)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 3',
        team2: 'Team 4',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 5',
        team2: 'Team 6',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 7',
        team2: 'Team 8',
        score1: 0,
        score2: 0,
        date: '24/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },

    // Week 1 - Valorant - Wednesday 26th March - Semi-Final Stage (Bo3)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },
    {
        team1: 'Team 3',
        team2: 'Team 4',
        score1: 0,
        score2: 0,
        date: '26/3/2025',
        time: 'TBD',
        week: 1,
        location: 'Court 1',
    },

    // Week 3 - Valorant - Wednesday 9th April - Grand Final Stage (Bo5)
    {
        team1: 'Team 1',
        team2: 'Team 2',
        score1: 0,
        score2: 0,
        date: '9/4/2025',
        time: '21:30',
        week: 3,
        location: 'Court 1',
    },
]
