export const futsal_female = [
    {
        team1: 'NANO+ADME',
        team2: 'AI+AERO',
        score1: 3,
        score2: 3,
        winner: 'Draw',
        date: '24/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'AI+AERO',
        team2: 'ICE',
        score1: 0,
        score2: 1,
        winner: 'ICE',
        date: '24/3/2025',
        time: '17:15',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'ICE',
        team2: 'NANO+ADME',
        score1: 6,
        score2: 5,
        winner: 'ICE',
        date: '24/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
]

export const futsal_male = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '3/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '3/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '3/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '3/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '3/4/2025',
        time: '19:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '8/4/2025',
        time: '16:30',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '8/4/2025',
        time: '17:10',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '8/4/2025',
        time: '17:50',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '8/4/2025',
        time: '18:30',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '8/4/2025',
        time: '19:10',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '17:10',
        week: 'Final',
        location: 'Court 1',
        status: 'On-going',
    },
]

export const basketball_male = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: '19:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '18:00',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '18:45',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '19:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:00',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:45',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '19:00',
        week: 'Finals',
        location: 'Court 1',
        status: 'On-going',
    },
]

export const basketball_female = [
    {
        team1: 'NANO+ADME',
        team2: 'AI+AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI+AERO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'NANO+ADME',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '19:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
]

export const chairball_female = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '19:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '19:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '16:30',
        week: 'Finals',
        location: 'Court 1',
        status: 'On-going',
    },
]

export const badminton_male = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },

    // Week 2 ====================================================================================================
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 3',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner of Quarter Final Match 2',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    //Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '17:50',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
]

export const badminton_female = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '16:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '16:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '16:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '17:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '18:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '18:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '18:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Finalist
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '31/3/2025',
        time: '18:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    //Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '17:50',
        week: '3',
        location: 'Court 2',
        status: 'On-going',
    },
]

export const rov_mixed = [
    // Quarter-Finals
    {
        team1: 'Team 1',
        team2: 'NiceTired',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'TeddyBearX2',
        team2: 'อุกะอุกะ',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'ADME di wa',
        team2: 'Conceptus Deletus',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'โดสเต่นโดสอ๊าย',
        team2: 'Team 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
    },

    // Semi-Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: 'Semi-Finals',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: 'Semi-Finals',
        location: '-',
        status: 'On-going',
    },

    // Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '20:00',
        week: 'Finals',
        location: '-',
        status: 'On-going',
    },
]

export const valorant_mixed = [
    // Quarter-Finals
    {
        team1: 'JubJimLimLay',
        team2: 'เฮียอ๊าท',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'ลงขำๆ',
        team2: 'Rush B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },

    // Semi-Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
    },

    // Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '21:30',
        week: '3',
        location: '-',
        status: 'On-going',
    },
]
