export const badminton_male = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner of Quarter Final Match 3',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },

    // Week 2 ====================================================================================================
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Quarter Finals
    {
        team1: 'Winner Match A',
        team2: 'Winner Match B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match C',
        team2: 'Winner Match D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    {
        team1: 'Winner Match E',
        team2: 'Winner Match F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner Match G',
        team2: 'Winner Match H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Semi Finals
    {
        team1: 'Winner of Quarter Final Match 1',
        team2: 'Winner of Quarter Final Match 3',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'Winner of Quarter Final Match 2',
        team2: 'Winner of Quarter Final Match 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
    },
    // Finalist
    {
        team1: 'Winner of Semi-Final Match 1',
        team2: 'Winner of Semi-Final Match 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    //Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '17:50',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
]
