export const badminton_male = [
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '16:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    // Quarter Finals
    {
        team1: 'Winner A',
        team2: 'Winner B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner C',
        team2: 'Winner D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner E',
        team2: 'Winner F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner G',
        team2: 'Winner H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:10',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 16',
    },
    // Semi Finals
    {
        team1: 'Winner QF 1',
        team2: 'Winner QF 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'Winner QF 3',
        team2: 'Winner QF 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 2',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    // Finalist
    {
        team1: 'Winner SF 1',
        team2: 'Winner SF 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: '18:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
        round: 'Semi Finals',
    },

    // Week 2 ====================================================================================================
    {
        team1: 'Player 1',
        team2: 'Player 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 3',
        team2: 'Player 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 5',
        team2: 'Player 6',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 7',
        team2: 'Player 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '16:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 9',
        team2: 'Player 10',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 11',
        team2: 'Player 12',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 13',
        team2: 'Player 14',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 32',
    },
    {
        team1: 'Player 15',
        team2: 'Player 16',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 32',
    },
    // Quarter Finals
    {
        team1: 'Winner A',
        team2: 'Winner B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner C',
        team2: 'Winner D',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner E',
        team2: 'Winner F',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Round of 16',
    },
    {
        team1: 'Winner G',
        team2: 'Winner H',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:10',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Round of 16',
    },
    // Semi Finals
    {
        team1: 'Winner QF 1',
        team2: 'Winner QF 3',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'Winner QF 2',
        team2: 'Winner QF 4',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 2',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    // Finalist
    {
        team1: 'Winner SF 1',
        team2: 'Winner SF 2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
        round: 'Semi Finals',
    },
    // Final
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '17:50',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
        round: 'Finals',
    },
]
