export const basketball_male = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 35,
        score2: 19,
        winner: 'NANO',
        date: '25/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 27,
        score2: 38,
        winner: 'AI',
        date: '25/3/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 32,
        score2: 23,
        winner: 'ADME',
        date: '25/3/2025',
        time: '19:30',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '18:00',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '18:45',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '1/4/2025',
        time: '19:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:00',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:45',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '19:00',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
]
