export const basketball_female = [
    {
        team1: 'NANO+ADME',
        team2: 'AI+AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI+AERO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '18:45',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'NANO+ADME',
        score1: 0,
        score2: 0,
        winner: '',
        date: '4/4/2025',
        time: '19:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
]
