export const chairball_female = [
    {
        team1: 'NANO',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '17:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '17:50',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '18:30',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: '19:10',
        week: '1',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '16:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ICE',
        team2: 'AERO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '17:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'ADME',
        team2: 'AI',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '17:50',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AERO',
        team2: 'NANO',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '18:30',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'AI',
        team2: 'ICE',
        score1: 0,
        score2: 0,
        winner: '',
        date: '2/4/2025',
        time: '19:10',
        week: '2',
        location: 'Court 1',
        status: 'On-going',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '16:30',
        week: '3',
        location: 'Court 1',
        status: 'On-going',
    },
]
