export const futsal_female = [
    {
        team1: 'NANO+ADME',
        team2: 'AI+AERO',
        score1: 3,
        score2: 3,
        winner: 'Draw',
        date: '24/3/2025',
        time: '16:30',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'AI+AERO',
        team2: 'ICE',
        score1: 0,
        score2: 1,
        winner: 'ICE',
        date: '24/3/2025',
        time: '17:15',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
    {
        team1: 'ICE',
        team2: 'NANO+ADME',
        score1: 6,
        score2: 5,
        winner: 'ICE',
        date: '24/3/2025',
        time: '18:00',
        week: '1',
        location: 'Court 1',
        status: 'Done',
    },
]
