export const rov_mixed = [
    // Quarter-Finals
    {
        team1: 'Team 1',
        team2: 'NiceTired',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'TeddyBearX2',
        team2: 'อุกะอุกะ',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'ADME di wa',
        team2: 'Conceptus Deletus',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'โดสเต่นโดสอ๊าย',
        team2: 'Team 8',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: 'Quarter-Finals',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },

    // Semi-Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: 'Semi-Finals',
        location: '-',
        status: 'On-going',
        round: 'Semi Finals',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: 'Semi-Finals',
        location: '-',
        status: 'On-going',
        round: 'Semi Finals',
    },

    // Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '20:00',
        week: 'Finals',
        location: '-',
        status: 'On-going',
        round: 'Finals',
    },
]
