export const rov_mixed = [
    // Quarter-Finals
    {
        team1: 'โดสเต่นโดสอ๊าย',
        team2: 'อุกะอุกะ',

        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'Conceptus Deletus',
        team2: 'ADME di wa',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'มายองเนส',
        team2: 'TeddyBearX2',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'ยังไม่มีชื่อกลุ่ม',
        team2: 'NiceTired',
        score1: 0,
        score2: 0,
        winner: '',
        date: '25/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Quarter Finals',
    },

    // Semi-Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Semi Finals',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '27/3/2025',
        time: 'TBD',
        week: '1',
        location: 'Online',
        status: 'On-going',
        round: 'Semi Finals',
    },

    // Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '20:00',
        week: '3',
        location: 'Online',
        status: 'On-going',
        round: 'Finals',
    },
]
