export const valorant_mixed = [
    // Quarter-Finals
    {
        team1: 'JubJimLimLay',
        team2: 'เฮียอ๊าท',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'ลงขำๆ',
        team2: 'Rush B',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '24/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Quarter Finals',
    },

    // Semi-Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Semi Finals',
    },
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '26/3/2025',
        time: 'TBD',
        week: '1',
        location: '-',
        status: 'On-going',
        round: 'Semi Finals',
    },

    // Finals
    {
        team1: 'TBD',
        team2: 'TBD',
        score1: 0,
        score2: 0,
        winner: '',
        date: '9/4/2025',
        time: '21:30',
        week: '3',
        location: '-',
        status: 'On-going',
        round: 'Finals',
    },
]
